# Generated by Django 6.1.1 on 2026-09-03 18:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misas', '0002_misa_created_at_misa_updated_at_templo_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servicio', models.PositiveSmallIntegerField(choices=[(1, 'Misa'), (2, 'Confesiones'), (3, 'Santisimo')])),
                ('dia_de_semana', models.PositiveSmallIntegerField(choices=[(1, 'Domingo'), (2, 'Lunes'), (3, 'Martes'), (4, 'Miercoles'), (5, 'Jueves'), (6, 'Viernes'), (7, 'Sabado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('templo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misas.templo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
