# Generated by Django 6.1 on 2026-09-01 05:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Templo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=1000)),
                (
                    "alias",
                    models.CharField(
                        max_length=100, verbose_name="otro nombre conocido"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Misa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dia_de_semana",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Domingo"),
                            (2, "Lunes"),
                            (3, "Martes"),
                            (4, "Miercoles"),
                            (5, "Jueves"),
                            (6, "Viernes"),
                            (7, "Sabado"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                (
                    "templo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="misas.templo"
                    ),
                ),
            ],
        ),
    ]
