# Generated by Django 6.1.1 on 2026-09-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misas", "0003_servicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="hora_fin",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
