# Generated by Django 6.1.1 on 2026-09-03 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("misas", "0006_alter_servicio_dia_de_semana_delete_misa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicio",
            old_name="servicio",
            new_name="tipo_servicio",
        ),
    ]
