# Generated by Django 6.1.1 on 2026-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misas', '0007_rename_servicio_servicio_tipo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templo',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='otro nombre conocido'),
        ),
    ]
