# Generated by Django 6.1.1 on 2026-09-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misas', '0010_remove_templo_imagen_url_templo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='templo',
            name='facebook',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='templo',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
